# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shopping_pb2 as shopping__pb2


class MarketServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterSeller = channel.unary_unary(
                '/MarketService/RegisterSeller',
                request_serializer=shopping__pb2.SellerRequest.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.SellItem = channel.unary_unary(
                '/MarketService/SellItem',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.UpdateItem = channel.unary_unary(
                '/MarketService/UpdateItem',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.DeleteItem = channel.unary_unary(
                '/MarketService/DeleteItem',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.DisplaySellerItems = channel.unary_unary(
                '/MarketService/DisplaySellerItems',
                request_serializer=shopping__pb2.SellerRequest.SerializeToString,
                response_deserializer=shopping__pb2.ItemList.FromString,
                )
        self.SearchItem = channel.unary_unary(
                '/MarketService/SearchItem',
                request_serializer=shopping__pb2.SearchRequest.SerializeToString,
                response_deserializer=shopping__pb2.ItemList.FromString,
                )
        self.BuyItem = channel.unary_unary(
                '/MarketService/BuyItem',
                request_serializer=shopping__pb2.BuyerRequest.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.AddToWishlist = channel.unary_unary(
                '/MarketService/AddToWishlist',
                request_serializer=shopping__pb2.BuyerRequest.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.RateItem = channel.unary_unary(
                '/MarketService/RateItem',
                request_serializer=shopping__pb2.BuyerRequest.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.notify_buyers = channel.unary_unary(
                '/MarketService/notify_buyers',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )
        self.notify_seller = channel.unary_unary(
                '/MarketService/notify_seller',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )


class MarketServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterSeller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SellItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisplaySellerItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuyItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToWishlist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RateItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def notify_buyers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def notify_seller(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterSeller': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSeller,
                    request_deserializer=shopping__pb2.SellerRequest.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'SellItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SellItem,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'UpdateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateItem,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'DeleteItem': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteItem,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'DisplaySellerItems': grpc.unary_unary_rpc_method_handler(
                    servicer.DisplaySellerItems,
                    request_deserializer=shopping__pb2.SellerRequest.FromString,
                    response_serializer=shopping__pb2.ItemList.SerializeToString,
            ),
            'SearchItem': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchItem,
                    request_deserializer=shopping__pb2.SearchRequest.FromString,
                    response_serializer=shopping__pb2.ItemList.SerializeToString,
            ),
            'BuyItem': grpc.unary_unary_rpc_method_handler(
                    servicer.BuyItem,
                    request_deserializer=shopping__pb2.BuyerRequest.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'AddToWishlist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToWishlist,
                    request_deserializer=shopping__pb2.BuyerRequest.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'RateItem': grpc.unary_unary_rpc_method_handler(
                    servicer.RateItem,
                    request_deserializer=shopping__pb2.BuyerRequest.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'notify_buyers': grpc.unary_unary_rpc_method_handler(
                    servicer.notify_buyers,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
            'notify_seller': grpc.unary_unary_rpc_method_handler(
                    servicer.notify_seller,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MarketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterSeller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/RegisterSeller',
            shopping__pb2.SellerRequest.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SellItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/SellItem',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/UpdateItem',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/DeleteItem',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisplaySellerItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/DisplaySellerItems',
            shopping__pb2.SellerRequest.SerializeToString,
            shopping__pb2.ItemList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/SearchItem',
            shopping__pb2.SearchRequest.SerializeToString,
            shopping__pb2.ItemList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BuyItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/BuyItem',
            shopping__pb2.BuyerRequest.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddToWishlist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/AddToWishlist',
            shopping__pb2.BuyerRequest.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RateItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/RateItem',
            shopping__pb2.BuyerRequest.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def notify_buyers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/notify_buyers',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def notify_seller(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MarketService/notify_seller',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class BuyerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyClient = channel.unary_unary(
                '/BuyerService/NotifyClient',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )


class BuyerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BuyerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyClient': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyClient,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BuyerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BuyerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BuyerService/NotifyClient',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class SellerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NotifyClient = channel.unary_unary(
                '/SellerService/NotifyClient',
                request_serializer=shopping__pb2.Item.SerializeToString,
                response_deserializer=shopping__pb2.Notification.FromString,
                )


class SellerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NotifyClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SellerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NotifyClient': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyClient,
                    request_deserializer=shopping__pb2.Item.FromString,
                    response_serializer=shopping__pb2.Notification.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SellerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SellerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NotifyClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SellerService/NotifyClient',
            shopping__pb2.Item.SerializeToString,
            shopping__pb2.Notification.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
